### ISSUE TITLE
Presentation to future users

### ISSUE THREAD

**Issue by salgorog** [bdrawe/put-a-ring-on-it#28]
* Slides created and reviewed by peers

* Slides show process making

* Slides portray team work

* Slides define end goal of the application

* Slides define future ideas & improvements

* Presentation includes a demo of the application

**Comment by bdrawe** [comment]
Here are the presentation requirements: 

    * Elevator pitch: A one-minute description of your application.

    * Concept: What is your user story? What was your motivation for development?

    * Process: What were the technologies used? How were tasks and roles broken down and assigned? What challenges did you encounter? What were your successes?

    * Demo: Show your stuff!

    * Directions for future development.

    * Links to the deployed application and the GitHub repository.
